FROM python:3.13-slim-bookworm

RUN apt-get update -qy && apt-get install -qyy \
    -o APT::Install-Recommends=false \
    ca-certificates curl \
    && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:0.6.6 /uv /usr/local/bin/uv

WORKDIR /svc

ENV UV_COMPILE_BYTECODE=0 \
    PYTHONPATH="/svc/src" \
    PATH="/svc/.venv/bin:$PATH"

RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=./uv.lock,target=uv.lock \
    --mount=type=bind,source=./pyproject.toml,target=pyproject.toml \
    --mount=type=bind,source=./.python-version,target=.python-version \
    uv sync --frozen --no-install-project

COPY . /svc

CMD ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001", "--reload", "--reload-dir", "/svc/src", "--reload-dir", "/svc/app"]
